### ISSUE TITLE
datepicker fonts

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#1356]
The fonts in the datepicker are not the same as the rest of the page
https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/third-party/jquery-ui/jquery-ui.css#L323
https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/third-party/jquery-ui/jquery-ui.css#L333

we should overwrite it with something like (in `contribs/gmf/less/base.less`):

``` css
.ui-widget {
  font-family: @font-family-base;
  button {
    font-family: @font-family-base;
  }
}
```
