### ISSUE TITLE
Add ngeo scope to CSS classes

### ISSUE THREAD

**Issue by gberaudo** [camptocamp/ngeo#1680]
CSS class names used in ngeo are not enough scoped and thus will cause conflicts.

For example, for the search directive, we use the class ".search" and the CSS defines a rule like:
```css
.search input {
  height: 100%;
}
```

This conflicts with any application or component using an `input` in a `search` class.

As a consequence, ngeo classes should be prefixed like this:

```css
.ngeo-search input {
  height: 100%;
}
```
