### ISSUE TITLE
Don't depends on closure-utils anymore - Use webpack?

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#2057]
Create our own tool who should be able to:

* Get the build dependencies (for make)
* Do the build including the external library in one shot, with downloading them
* Be able to create a custom build that extends a generic build
* Easily generate what we needs for the dynamic loading
* Set correctly the source map

Use: 
* https://www.npmjs.com/package/google-closure-compiler
* webpack
* https://github.com/google/closure-compiler-js#webpack

Proposed YAML configuration file (Should be rework to use webpack):
<s>
```yaml
extends: ...
external_lib: [...] should be append to the build file
closure options: ... as dictionary
  src: [...] should be extended instance overwrite
  # same for externs, define, jscomp_off, extra_annotation_name
```

All the path should be like:
`<npm_package>/<path>`
then we transform it in `mode_modules/<npm_package>/<path>`
but we can add an option like `--path ngeo=.` then `ngeo/<path>` should be transform as `./<path>`.
If we find a way to do it automatically it's can be great :-).

The inheritance should replace having a mako file...

The entry point should be provide in the command line.

We should a way to easily build in whitespace mode, proposal file format:
```yaml
extends: ...
<build-type>:
   external_lib: [...]
   closure options: {...}
```
and add --build-type option
</s>

Dependencies size and module system:
```
jsts                        437k    es6
angular                     159k    one file, sources: no
@angular/core               186k    es6, (typescript is converted in js)
d3                          149k    es6
d3v4                        209k    es6
jquery-ui                   94k     no modules
jquery                      84k     commonjs
jquery3                     85k     commonjs
proj4                       74k     no modules (not needed)
corejs-typeahead            44k     no modules
bootstrap                   37k     no modules (dificult to select?)
angular-animate             26k     one file
floatthead                  15k     one file
angular-ui-slider           11k     one file
angular-ui-date             9.6k    one file
angular-sanitize            5.8k    one file
angular-gettext             5.7k    one file
angular-touch               4.0k    one file
angular-float-thead         3.0k    one file
angular-dynamic-locale      3.1k    one file
file-saver                  2.4k    one file
```
