### ISSUE TITLE
Rework on the mobile.less

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#439]
In contrib/gmf/apps/mobile/less/mobile.less we should have something like:
```less
@import '../../../less/mobile-base.less';
@import '../../../less/search.less';
```
we should move:
`nav.less` -> `mobile-nav.less`

and we should create:
`base.less` with:
```less
@import (inline) '../../../node_modules/openlayers/css/ol.css';
@import (inline) '../css/reset.css';
@import '../../../node_modules/bootstrap/less/bootstrap.less';

@import 'vars.less';

body {
  overflow: hidden;
}

a {
  text-decoration: none;
}
```
`mobile-base.less` with:
```less
@import 'base.less';
@import 'map.less';
@import 'mobile-nav.less';
```
